version: '3'

services:
  pexad:
    image: pexacoin/core:latest
    command: pexad --printtoconsole
    build:
      context: .
    volumes:
    #   - /home/pexa/.pexa:/root/.pexa
      - ./docker-entrypoint.sh:/entrypoint.sh
    ports:
      - 18770:18770
      - 2300:2300
      - 8235:8235
    environment:
      - UID=1001 
      - GID=1001
